### ISSUE TITLE
magit-git-command is called by 2 args instaed of 1 by magit-annex-command

### ISSUE THREAD

**Issue by emelin** [magit/magit-annex#16]
Hello, 
when trying to execute @ : = Annex subcommand (from pwd) the following error occurs:

    Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
     magit-git-command("annex info" "/some_path/")
    apply(magit-git-command ("annex info" "/some_path/"))
    magit-annex-command()
    funcall-interactively(magit-annex-command)
    ....

Somebody might have overseen to adjust the apply command.

**Comment by kyleam** [comment]
Yep, it needs to be adjusted for Magit's b1b7798f
(magit-shell-command-topdir: return only the read command,
2017-04-03).

Thanks
