### ISSUE TITLE
Flaky test suite

### ISSUE THREAD

**Issue by spwhitton** [magit/magit-annex#19]
Hello,

We are running magit-annex's test suite on Debian's CI infrastructure.  While the tests usually pass we have noticed that every so often a test fails with the following error:

    (user-error "Not inside a Git repository")

A quick look at the logs shows this happening with several different of the ten ERT tests.  Full logs are [here](https://ci.debian.net/packages/m/magit-annex/unstable/amd64/) (scroll down that page and look for "thumbs down" icons).

Please let me know if I can help debug.  For now, I am disabling the test suite on our CI infrastructure.  We already have it disabled during the package build process due to the same error.

**Comment by kyleam** [comment]
Thanks for notifying me.  I'll look into it.

**Comment by kyleam** [comment]
Should be fixed.  Please let me know if the error pops up again.

**Comment by kyleam** [comment]
Ehh, I took the sledgehammer approach and ran a lot of tests locally to gain confidence that there weren't any more sporadic errors.   But now the second test of the just-set-up Travis failed (with a different but similar error).  I'll have to take another look later.

**Comment by kyleam** [comment]
OK, I hope that does it.  Could you please re-enable the tests on Debian's CI infrastructure?

**Comment by spwhitton** [comment]
Hello,

On Sun 15 Jul 2018 at 06:31PM -0700, Kyle Meyer wrote:

> OK, I hope that does it.  Could you please re-enable the tests on Debian's CI infrastructure?

I will do an upload to our experimental repository and let you know the results.

-- 
Sean Whitton

**Comment by spwhitton** [comment]
[Look for results for 1.6.0-2~exp1 on this page](https://ci.debian.net/packages/m/magit-annex/unstable/amd64/).  Looks like the fix is working; I will trigger the tests a few more times before moving it from experimental to the main repo.  Thank you!
