### ISSUE TITLE
Question: How to mv file (symlink) to another dir in the same repo without unlocking it

### ISSUE THREAD

**Issue by QiangF** [magit/magit-annex#22]
This could be useful for restructuring the dir structures.

**Comment by kyleam** [comment]
You can `git mv <src> <dst>` (and you can do that from Magit with `magit-file-rename`).  If the move is to a different directory, the symlink will be temporarily broken, but git-annex will repair it when the pre-commit hook runs.

**Comment by QiangF** [comment]
Thank you! I think relinking relative symlinks in dired is a better idea.

**Comment by QiangF** [comment]
I solve this with an advice for rename-file.

    (defun my-rename-file (file newname &optional ok-if-already-exists)
    "fix path for relative symlink"
    (let ((target (expand-file-name (file-symlink-p newname) (file-name-directory file))))
          (if (and target (string-equal system-type "gnu/linux") (not (file-exists-p newname))) 
              (dired-make-relative-symlink target newname t))))
    (advice-add #'rename-file :after #'my-rename-file)

I am quite new to emacs, I am not sure if the above has any side
effect. There are some complicated examples of dealing with
symlink : https://www.emacswiki.org/emacs/symlink-fix.el I am not
sure if windows has relative shortcuts. This link show you can
use symlinks in windows:
https://github.com/sensorflo/sensorflo-emacs/blob/master/site-lisp/w32-symlinks.el
