### ISSUE TITLE
magit-annex-unlock-lock-files test fails in v7 repos

### ISSUE THREAD

**Issue by spwhitton** [magit/magit-annex#23]
Hello,

I think the magit-annex-unlock-lock-files test needs to be updated for the way that unlocked files work in v7 git-annex repos (which is the new default).

The fourth line of the test, `(should-not (magit-annex-unlocked-files))`, fails because committing changes to an unlocked file no longer locks it.

Thanks!

**Comment by kyleam** [comment]
Thanks for reporting the failure.  It should now be resolved on master.

**Comment by spwhitton** [comment]
Hello,

On Sun 23 Feb 2020 at 04:13PM -08, Kyle Meyer wrote:

> Thanks for reporting the failure.  It should now be resolved on master.

Thank you.  It would be cool if you could consider tagging a new release
of magit; it's been a while.

-- 
Sean Whitton

**Comment by kyleam** [comment]
> It would be cool if you could consider tagging a new release of magit; it's been a while.

Magit v3.0.0 shouldn't be too far off: https://github.com/magit/magit/issues/3918#issuecomment-582339032

**Comment by spwhitton** [comment]
Hello,

On Sun 23 Feb 2020 at 05:35PM -08, Kyle Meyer wrote:

>> It would be cool if you could consider tagging a new release of magit; it's been a while.
>
> Magit v3.0.0 shouldn't be too far off: https://github.com/magit/magit/issues/3918#issuecomment-582339032

I'm sorry, I meant of magit-annex :)

-- 
Sean Whitton

**Comment by kyleam** [comment]
> I'm sorry, I meant of magit-annex :)

The release of magit-annex's master branch is currently coupled to the next release of magit, primarily due to the switch from magit-popup to transient.  While I didn't avoid that coupling by keeping a maintenance branch, I could cherry pick 9ffebd5 (magit-annex-unlocked-files: Rewrite for v6+ compatibility, 2020-02-23) on top of v1.7.1 and make a release if it'd be useful for Debian packaging purposes, though I imagine at this point it probably just makes sense to wait for a magit release.

**Comment by spwhitton** [comment]
Hello,

On Mon 24 Feb 2020 at 03:14PM -08, Kyle Meyer wrote:

>> I'm sorry, I meant of magit-annex :)
>
> The release of magit-annex's master branch is currently coupled to the next release of magit, primarily due to the switch from magit-popup to transient.  While I didn't avoid that coupling by keeping a maintenance branch, I could cherry pick 9ffebd5 (magit-annex-unlocked-files: Rewrite for v6+ compatibility, 2020-02-23) on top of v1.7.1 and make a release if it'd be useful for Debian packaging purposes, though I imagine at this point it probably just makes sense to wait for a magit release.

Happy to wait.  Thanks for the info.

-- 
Sean Whitton
