### ISSUE TITLE
Magit annex fails to process specified file names matching the regexp [[,]

### ISSUE THREAD

**Issue by spacebat** [magit/magit-annex#25]
In the case of a file with [ in its name, it is treated as a wildcard, expanded and then doesn't match the actual file, so we get nil.

In the case of a file with a comma in its name, `completing-read-multiple` treats each such file name as multiple files because it splits on the comma, and then git-annex fails to find the files.

I have PRs to make for each case if you'd like.

**Comment by kyleam** [comment]
> I have PRs to make for each case if you'd like.

Sure, thanks in advance.  One PR with separate commits sounds like it'd be appropriate in this case.

**Comment by spacebat** [comment]
See #26

**Comment by kyleam** [comment]
The associated PR was closed as stale.  Closing this issue too, though I'm happy to revisit if there's interest.
