### ISSUE TITLE
Default keybinding conflicts with Forge

### ISSUE THREAD

**Issue by hpfr** [magit/magit-annex#37]
The Forge extension for Magit also uses `@` as a default prefix. magit-annex is certainly older, and keeping consistent with the dired extension seems desirable. On the other hand, Forge is fairly popular these days, and it would be nice for magit-annex not to conflict with it out of the box.

Of course, users can rebind the magit-annex prefix if they want. But what do you think about changing the default prefix to accomodate Forge? Feel free to close this issue if you think maintaining consistency for existing users takes precedence, but maybe a note with a suggested override config could be added to the package frontmatter, or the hardcoded `@` autoload could be changed to use a custom variable?

**Comment by tarsius** [comment]
Forge doesn't use `@` by default and as far as I can tell it never did.

**Comment by hpfr** [comment]
You're absolutely right; turns out it's an `evil-collection` binding to free up `N` for searching backwards. Thanks, I should've verified that.

**Comment by hpfr** [comment]
For future searchers, `&` is available (in Vim, it modifies the buffer, so it doesn't lose you anything in Magit buffers) and quite mnemonic, both phonetically in English and semantically, considering that git-annex extends git with support for large files. `@` feels semantically right for Forge anyway.

Here's what I wrote to override things accordingly. It contains Doomisms, but it shouldn't be hard to translate.
```elisp
;; move magit-annex from @ to & to accomodate forge
(after! magit
  (map! :map magit-mode-map
        "&" #'magit-annex-dispatch)
  (transient-append-suffix 'magit-dispatch '(0 -1 -1)
    '("&" "Annex" magit-annex-dispatch)))
;; despite the autoload after magit in magit-annex.el, the @ binding seems to
;; happen after magit-annex loads, so overwrite it then
(after! magit-annex
  (map! :map magit-mode-map
        "@" #'forge-dispatch)
  (transient-replace-suffix 'magit-dispatch "@"
    '("@" "Forge" forge-dispatch)))
```

Would you be open to a PR creating a custom variable for the prefix so that users don't have to overwrite the binding manually after magit-annex loads?
