### ISSUE TITLE
Feature request : support for magit-post-stage-hook 

### ISSUE THREAD

**Issue by nicolas-graves** [magit/magit-annex#38]
I'm trying to get a worklfow were commits are automated with the help of the magit-post-stage-hook, with context-aware commits. However, this hook is not run when running git-annex-add on a file. 

I believe it would make sense to support this hook when running git-annex-add, because it does indeed stage the git-annex symlink.

**Comment by kyleam** [comment]
> I believe it would make sense to support this hook when running git-annex-add

Yes, that makes sense to me too.  I'll look into doing that this weekend.  (You're of course welcome to beat me to it, in which case I'll be happy to look at your PR this weekend.)

**Comment by kyleam** [comment]
I had assumed that it would be inserting a `run-hooks` call, but, taking a look at `magit-post-stage-hook`, it's called by `magit-run-post-stage-hook`:

```elisp
(defun magit-run-post-stage-hook ()
  (when (memq this-command magit-post-stage-hook-commands)
    (magit-run-hook-with-benchmark 'magit-post-stage-hook)))
```

And that is a part of `magit-post-refresh-hook`.

So you can get the `annex add` commands in there with

```elisp
(setq magit-post-stage-hook-commands
      (append '(magit-annex-add magit-annex-add-all)
              magit-post-stage-hook-commands))
```

I'm undecided on whether magit-annex should do that itself.

**Comment by kyleam** [comment]
> I'm undecided on whether magit-annex should do that itself.

At least for the time being, I'll leave it to interested users to adjust `magit-post-stage-hook-commands` in their configs.

**Comment by nicolas-graves** [comment]
Thanks for the tip, sorry for the late answer ! 
Thanks again for magit-annex, I use it every day ;)
